name: deploy website

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.89.4/hugo_0.89.4_Linux-64bit.deb
        sudo dpkg -i hugo_0.89.4_Linux-64bit.deb
        sudo apt-get install -f
    - name: check hugo version
      run: hugo version

    - uses: actions/checkout@v2

    - name: echo working directory
      run: echo ${{ github.workspace }}
    - name: build
      run: |
        cd ${{ github.workspace }}
        pwd
        ls -l
        hugo -D
        ls -l public
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

