name: deploy website

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: check hugo version
      run: hugo version

    - name: echo working directory
      run: echo ${{ github.workspace }}

    - name: build
      run: |
        cd ${{ github.workspace }}
        pwd
        ls -l
        hugo -D
        ls -l public

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

