name: deploy

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # add the private key to the ssh-agent
    # the private repo is referenced via ssh so the key will be used
    # from the agent when doing the checkout
    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: update content
      run: |
        cd ${{ github.workspace }}/content
        git log -n 1
        git checkout master
        git log -n 1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: check hugo version
      run: hugo version

    - name: echo working directory
      run: echo ${{ github.workspace }}

    - name: build
      run: |
        cd ${{ github.workspace }}
        pwd
        ls -l
        hugo -D
        ls -l public

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

